### ISSUE TITLE
Unexpected end of JSON input in metalwar

### ISSUE THREAD

**Issue by Thappers** [mann0000/wax-game-bots#4]
I thought this problem had righted itself but I’m getting this error every time now and it seems completely random as to which units it affects. Some units will raid, some will not. When I catch it:

fetchError: invalid json response body at https://wax.greymass.com/v1/chain/push_transaction reason: unexpected end of JSON input

any clues?

Edit: it works if I send the requests individually. I have quite a large army so it seems the API is being overloaded somehow. Needs to be some sort of delay between requests but I can’t figure out how to implement that correctly in the async function.

**Comment by mann0000** [comment]
Hi Thappers,

Thanks for your interest and your issues!

As you know, the script uses RPC relays (by default Greymass) to broadcast your transactions. Public nodes are more or less reliable and often throttle requests if you make them too often. The error message "fetchError: invalid json" indicates something goes wrong on the relay side.

The workaround is to replace the RPC endpoint by another one. I never find an updated list for Wax, but here are my favorite:
- https://wax.pink.gg
- https://api.waxsweden.org
- https://wax.eosrio.io

In order to minimise relay issues, I suggest you to run the script periodically, for instance every 10 minutes. If you run the script on a server, a cron job is perfect. It works also for your [previous issue](https://github.com/mann0000/wax-game-bots/issues/3).

**Comment by Thappers** [comment]
Thanks very much for your reply, I knew nothing of nodejs but your scripts have inspired me to learn. Am getting there :)
